Amazon S3 backup support integration pt. 1

diff --git a/bin/v-backup-user b/bin/v-backup-user
--- a/bin/v-backup-user
+++ b/bin/v-backup-user
@@ -45,6 +45,15 @@ if [ -z "$BACKUP" ]; then
 fi
 mkdir -p $BACKUP
 
+if [ "$BACKUP_SYSTEM" = 's3' ]; then
+    if [ ! -x /usr/bin/s3fs ]; then
+        echo "Error: s3fs binary non found!" >> $log
+        exit 1
+    fi
+    # Mount s3 bucket
+    /usr/bin/s3fs $S3BUCKET $BACKUP -o use_cache=/tmp -o passwd_file=$VESTA/conf/s3passwd
+fi
+
 # Get current time
 start_time=$(date '+%s')
 
@@ -869,6 +878,11 @@ echo "$backup_str" >> $USER_DATA/backup.conf
 tail -n $BACKUPS $USER_DATA/backup.conf > $USER_DATA/backup.conf_
 mv -f $USER_DATA/backup.conf_ $USER_DATA/backup.conf
 chmod 660 $USER_DATA/backup.conf
+
+if [ "$BACKUP_SYSTEM" = 's3' ]; then
+    # Unmount s3 bucket
+    umount /home/backup
+fi
 
 # Deleting task from queue
 sed -i "/v-backup-user $user /d" $VESTA/data/queue/backup.pipe
diff --git a/bin/v-restore-user b/bin/v-restore-user
--- a/bin/v-restore-user
+++ b/bin/v-restore-user
@@ -36,6 +36,15 @@ source $VESTA/func/db.sh
 source $VESTA/func/rebuild.sh
 source $VESTA/conf/vesta.conf
 
+if [ "$BACKUP_SYSTEM" = 's3' ]; then
+    if [ ! -x /usr/bin/s3fs ]; then
+        echo "Error: s3fs binary non found!" >> $log
+        exit 1
+    fi
+    # Mount s3 bucket
+    /usr/bin/s3fs $S3BUCKET $BACKUP -o use_cache=/tmp -o passwd_file=$VESTA/conf/s3passwd
+fi
+
 # Check backup function
 is_backup_valid() {
     if [ ! -e "$BACKUP/$backup" ]; then
@@ -822,6 +831,11 @@ fi
 
 # Remove temporary data
 rm -rf $tmpdir
+
+if [ "$BACKUP_SYSTEM" = 's3' ]; then
+    # Unmount s3 bucket
+    umount /home/backup
+fi
 
 # Clean restore queue
 sed -i "/v-restore-user $user /d" $VESTA/data/queue/backup.pipe
